/*
** DELOS PROJECT, 2025
** src/kernel/fs/vfs/vfs_lookup
** File description:
** VFS lookup source file
*/

#include <kernel/fs/vfs/vfs_registry.h>
#include <kernel/fs/vfs/vfs.h>

/**
 * @brief Lookup a node and try to find another level.
 *
 * @param node           The current node to go through (a dir for example)
 * @param next_level     The next level to lookup (e.g. node = "/", nextlevel = "abc", result = "/abc")
 *
 * @return The new node generated by the lookup callback.
 */
vfs_node_t *
kvfs_lookup(vfs_node_t *node, const char *next_level)
{
    return node->_ops->_lookup(node, next_level);
}
