/*
** DELOS PROJECT, 2025
** src/kernel/fs/vfs/vfs_lookup
** File description:
** VFS lookup source file
*/

#include <kernel/fs/vfs/vfs_registry.h>
#include <kernel/fs/vfs/vfs.h>

/**
 * @brief Lookup a node and try to find another level.
 *
 * @param node           The current node to go through (a dir for example)
 * @param next_level     The next level to lookup (e.g. node = "/", nextlevel = "abc", result = "/abc")
 *
 * @return The new node generated by the lookup callback.
 */
vfs_node_t *
kvfs_lookup(vfs_node_t *node, const char *next_level)
{
    const cred_t cred = {0, 0};
    vfs_stat_t st = {0};

    if (node == NULL || next_level == NULL) {
        return NULL;
    }
    if (kvfs_get_stat(node, &st) == KO_FALSE) {
        return NULL;
    }
    if (kvfs_stat_can_exec(&st, &cred) == KO_FALSE) {
        return NULL;
    }
    return node->_ops->_lookup(node, next_level);
}
